apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  namespace: tensure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-node
          image: vamckrish08/kubernetes:1