apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tensure-issuer
  namespace: ${namespace}
spec:
  acme:
    # The ACME server URL
    server: ${SERVER}
    # Email address used for ACME registration
    email: ${EMAIL}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: tensure-issuer
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        cloudDNS:
          project: vamsi-krishna-sandbox