apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: ${namespace}
  annotations:
    cert-manager.io/cluster-issuer: tensure-issuer
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
