apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
  namespace: tensure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: second-node
          image: vamckrish08/kubernetes:1