apiVersion: v1
kind: Secret
metadata:
  name: wildcard-cert-secret-second
  namespace: tensure
  annotations:
    cert-manager.io/cluster-issuer: tensure-issuer
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
