apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tensure-issuer-duration
  namespace: tensure
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory #staging url for custom cert duration
    # Email address used for ACME registration
    email: vamsi.krishna@tensure.io
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: tensure-issuer-duration
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        cloudDNS:
          project: vamsi-krishna-sandbox