apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: tensure
spec:
  secretName: wildcard-cert-secret
  dnsNames:
    - "*.ioinfo.shop"
  issuerRef:
    name: tensure-issuer
    kind: ClusterIssuer
  
