apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: local-1
        url: https://kubernetes.default.svc
        path: manifests/apps-of-apps/app-1-manifest/
      - cluster: local-2
        url: https://kubernetes.default.svc
        path: manifests/apps-of-apps/app-2-helm/
  template:
    metadata:
      name: '{{cluster}}-application'
    spec:
      project: default
      source:
        repoURL: https://github.com/Tensure/td-cert-manager.git
        targetRevision: version-1
        path: {{path}}
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true