---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: local-1
            url: https://kubernetes.default.svc
            path1: manifests/apps-of-apps/app-1-manifest/
            path2: manifests/base/argo-demo/
          # - cluster: local-2
          #   url: https://kubernetes.default.svc
          #   path: manifests/apps-of-apps/app-2-helm/
  template:
    metadata:
      name: "{{cluster}}-application"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Tensure/td-cert-manager.git
          targetRevision: version-1
          path: "{{path1}}"
          directory:
            recurse: true
            exclude: properties.yaml
        - repoURL: https://github.com/Tensure/td-cert-manager.git
          targetRevision: version-1
          path: "{{path2}}"
          directory:
            recurse: true
            exclude: properties.yaml
      destination:
        server: "{{url}}"
        namespace: "{{cluster}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true