---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app2-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: local-argo
            url: https://kubernetes.default.svc
            path1: manifests/base/argo-ingress/
          # - cluster: local-2
          #   url: https://kubernetes.default.svc
          #   path: manifests/apps-of-apps/app-2-helm/
  template:
    metadata:
      name: "{{cluster}}-application2"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Tensure/td-cert-manager-app-config.git
          targetRevision: main
          path: "{{path1}}"
          directory:
            recurse: true
            exclude: properties.yaml
      destination:
        server: "{{url}}"
        namespace: "argocd"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true