---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app3-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: local-3
            url: https://kubernetes.default.svc
            path1: manifests/apps-of-apps/nginx/
            path2: manifests/base/nginx-ingress/
  template:
    metadata:
      name: "{{cluster}}-application"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Tensure/td-cert-manager-app-config.git
          targetRevision: main
          path: "{{path1}}"
          directory:
            recurse: true
            exclude: properties.yaml
        - repoURL: https://github.com/Tensure/td-cert-manager-app-config.git
          targetRevision: main
          path: "{{path2}}"
          directory:
            recurse: true
            exclude: properties.yaml
      destination:
        server: "{{url}}"
        namespace: "nginx"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true