---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app4-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: manual
            url: https://kubernetes.default.svc
            path1: manifests/without-cert-manager/nginx
  template:
    metadata:
      name: "{{cluster}}-application"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/Tensure/td-cert-manager-app-config.git
          targetRevision: main
          path: "{{path1}}"
          directory:
            recurse: true
            exclude: properties.yaml
      destination:
        server: "{{url}}"
        namespace: "manual"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true