apiVersion: v1
kind: Secret
metadata:
  name: demo-secret-argo
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: demo-issuer-argo
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
